DATASET:
  CLASS: UEADataset
  PARAM:
    name: Libras
    path: ./dataset/Multivariate2018_npz
  bands: 5
  fs: 0
EXPERIMENT:
  BATCH_SIZE: 64
  EPOCHS: 200
  OPTIMIZER:
    CLASS: SGD
    PARAM:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0005
  SCHEDULER:
    CLASS: ReduceLROnPlateau
    PARAM:
      cooldown: 0
      eps: 8.0e-09
      factor: 0.5
      min_lr: 1.0e-06
      mode: min
      patience: 10
      threshold: 4.0e-05
      threshold_mode: rel
      verbose: false
GRAPH:
  ADJ_MATRIX: mutual_information
  NODE: raw
MODEL:
  CLASS: GCN
  PARAM:
    dropout: 0.1
    graphlearn: false
    hidden_dim: 128
    in_dim: 45
    len: 45
    mlp_dim: 128
    n_classes: 15
    n_layers: 3
    residual: true
    t_embedding: 128
SYSTEM:
  GPU: 7
  NUM_WORKERS: 10
  SEED: 42
